<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '29e8544094c69e18bbce2c0abad2289d',
  'DATABASE_URL' => 'mysql://elvariand:amazingCandidate1993@db:3306/adimeoAPOD?serverVersion=8.2.0&charset=utf8mb4',
  'ALT_DATABASE_URL' => 'mysql://elvariand:amazingCandidate1993@127.0.0.1:4306/adimeoAPOD?serverVersion=8.2.0&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
);
